/*
 * File: MyViewport.ui.js
 * Date: Mon May 20 2013 17:14:53 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                style: '',
                bodyStyle: 'padding:10px;background: black; color:white; height:auto;',
                items: [
                    {
                        xtype: 'container',
                        width: 22,
                        height: 22,
                        style: 'background-image:url(http://www.sistemassacsa.com/images/trailer.png);'
                    },
                    {
                        xtype: 'container',
                        style: 'display: inline; float:right;',
                        items: [
                            {
                                xtype: 'displayfield',
                                value: 'Zesar X',
                                style: 'display:inline-block;float:left;'
                            },
                            {
                                xtype: 'container',
                                width: 16,
                                height: 16,
                                style: 'display:inline-block; float:rght; background: black;'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        text: 'Empresa de Pruebas'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                activeTab: 0,
                iconCls: '',
                defaults: {
                    closable: true
                },
                items: [
                    {
                        xtype: 'tabpanel',
                        title: 'Diario',
                        activeTab: 0,
                        iconCls: 'icoTab_Diario',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Busqueda',
                                items: [
                                    {
                                        xtype: 'editorgrid',
                                        title: 'My Grid',
                                        height: 288,
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'string',
                                                header: 'Carro',
                                                sortable: true,
                                                width: 100,
                                                editor: {
                                                    xtype: 'textfield'
                                                }
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'number',
                                                header: 'Cantidad',
                                                sortable: true,
                                                width: 100,
                                                align: 'right',
                                                editor: {
                                                    xtype: 'numberfield'
                                                }
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'date',
                                                header: 'Concepto',
                                                sortable: true,
                                                width: 100,
                                                editor: {
                                                    xtype: 'datefield'
                                                }
                                            },
                                            {
                                                xtype: 'booleancolumn',
                                                dataIndex: 'bool',
                                                header: 'Fecha',
                                                sortable: true,
                                                width: 100,
                                                editor: {
                                                    xtype: 'checkbox',
                                                    boxLabel: 'BoxLabel'
                                                }
                                            }
                                        ],
                                        tbar: {
                                            xtype: 'toolbar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'MyButton'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'MyButton'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'MyButton'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'MyButton'
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Edicion',
                                tbar: {
                                    xtype: 'toolbar'
                                },
                                items: [
                                    {
                                        xtype: 'form',
                                        title: 'My Form'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Envios',
                        iconCls: 'icoTab_Envio'
                    },
                    {
                        xtype: 'panel',
                        title: 'Clientes'
                    },
                    {
                        xtype: 'panel',
                        title: 'Conceptos'
                    },
                    {
                        xtype: 'panel',
                        title: 'Vehiculos',
                        iconCls: 'icoTab_Trailer'
                    },
                    {
                        xtype: 'panel',
                        title: 'Cajas'
                    },
                    {
                        xtype: 'panel',
                        title: 'Choferes',
                        iconCls: 'icoTab_Chofer'
                    },
                    {
                        xtype: 'panel',
                        title: 'Rutas'
                    },
                    {
                        xtype: 'panel',
                        title: 'Guias de entrega'
                    }
                ]
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
